<?php

define('MYPARCEL_PLUGIN_VERSION', '2.1.0');
define('ERROR_MESSAGE_CREDENTIAL', 'Incorrect client id or secret.');
define('MYPARCEL_METHOD', 'myparcel');
define('EXPORT_MYPARCEL_ORDER_TEXT', 'export_myparcel_order');
define('PRINT_LABEL_ORDER_TEXT', 'print_label_shipment');
define('SHIPMENT_PLUGIN_NOTICE', 'alive');
define('ORDER_TYPE_TEXT', 'Shipped by');
define('SHIPPED_STATUS_TEXT', 'Is partially shipped');
define('SHIPPED_LABEL', 'Label');
define('SHIPMENT_STATUS', 'Shipment Status');
define('EXPORT_ORDER_TO_MYPARCELCOM_TEXT', 'Export orders to MyParcel.com');
define('PRINT_LABEL_SHIPMENT_TEXT', 'Print MyParcel.com label');
define('GET_META_MYPARCEL_SHIPMENT_KEY', 'myparcel_shipment_key');
define('GET_META_SHIPMENT_TRACKING_KEY', 'shipment_track_key');
define('IS_EXISTS_TEXT', 'Exists');
define('NOT_FOUND_TEXT', 'Not found');
define('SHIPPED_TEXT', 'shipped');
define('GET_META_MYPARCEL_ORDER_META', 'myparcel_order_meta');
define('GET_META_MYPARCEL_ORDER_SHIPMENT_TEXT', '_my_parcel_order_shipment');
define('MYPARCEL_SUPPORT_TEXT_AND_URL', 'https://myparcel-com.odoo.com/en/woocommerce');
define('MYPARCEL_API_SETTING_TEXT', 'MyParcel.com API');
define('MYPARCEL_API_CLIENTID_LABEL_TEXT', '* Client ID');
define('MYPARCEL_API_CLIENTSECRET_LABEL_TEXT', '* Client secret');
define('MYPARCEL_API_ACT_TESTMODE_TEXT', 'Activate testmode');
define('MYPARCEL_API_TEXT', 'MyParcel.com');
define('MYPARCEL_API_CURRENT_VERSION', 'Current version');
define('MYPARCEL_API_SUPPORT_TEXT', 'MyParcel.com support');
define('MYPARCEL_PARTIALLY_SHIPPED_TEXT', 'Yes.');
define('MYPARCEL_FULLY_SHIPPED_TEXT', 'No');
define('MYPARCEL_NA_TEXT', 'NA');
define('MYPARCEL_SETTING_SAVE_TEXT', 'Settings saved.');
define('MYPARCEL_WEBHOOK_URL', 'https://sandbox-api.myparcel.com/hooks');
define('MYPARCEL_WEBHOOK_ACCESS_TOKEN', 'https://sandbox-auth.myparcel.com/access-token');
define('MYPARCEL_SHIPMENT_REGISTERED', 'shipment-registered');
define('MYPARCEL_SHIPMENT_LABEL_NOT_AVAILABLE', 'Label is not available yet.');
define('MYPARCEL_WEBHOOK_OPTION_ID', 'myparcel_web_hook_id');
define('MYPARCEL_RESPONSE_META', 'webhook_response_meta');
define('MYPARCEL_FAILED_TEXT', 'Failed');
define('MYPARCEL_WEBHOOK_RESPONSE', 'webhook_response_option');
define('MYPARCEL_SHOPID', 'Default Shop');
define('MYPARCEL_SHOPID_HELPTEXT', 'Please select the related MyParcel.com shop for this Wordpress Shop.');
